In [1]:
import pandas as pd
import numpy as np
import statsmodels.formula.api as smf
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.api as sm

health = pd.read_csv('Mental health Depression disorder Data.csv')

/var/folders/qs/k20tf5tx1g95_rd5zfrm_4nw0000gn/T/ipykernel_17547/300513165.py:8: DtypeWarning: Columns (5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  health = pd.read_csv('Mental health Depression disorder Data.csv')

In [2]:
health.head()

,index,Entity,Code,Year,Schizophrenia (%),Bipolar disorder (%),Eating disorders (%),Anxiety disorders (%),Drug use disorders (%),Depression (%),Alcohol use disorders (%)
0,0,Afghanistan,AFG,1990,0.16056,0.697779,0.101855,4.828830,1.677082,4.071831,0.672404
1,1,Afghanistan,AFG,1991,0.160312,0.697961,0.099313,4.829740,1.684746,4.079531,0.671768
2,2,Afghanistan,AFG,1992,0.160135,0.698107,0.096692,4.831108,1.694334,4.088358,0.670644
3,3,Afghanistan,AFG,1993,0.160037,0.698257,0.094336,4.830864,1.705320,4.096190,0.669738
4,4,Afghanistan,AFG,1994,0.160022,0.698469,0.092439,4.829423,1.716069,4.099582,0.669260

In [4]:
print(health['Entity'].unique()) # choose 10 countries to analyze + US

['Afghanistan' 'Albania' 'Algeria' 'American Samoa' 'Andean Latin America'
 'Andorra' 'Angola' 'Antigua and Barbuda' 'Argentina' 'Armenia'
 'Australasia' 'Australia' 'Austria' 'Azerbaijan' 'Bahamas' 'Bahrain'
 'Bangladesh' 'Barbados' 'Belarus' 'Belgium' 'Belize' 'Benin' 'Bermuda'
 'Bhutan' 'Bolivia' 'Bosnia and Herzegovina' 'Botswana' 'Brazil' 'Brunei'
 'Bulgaria' 'Burkina Faso' 'Burundi' 'Cambodia' 'Cameroon' 'Canada'
 'Cape Verde' 'Caribbean' 'Central African Republic' 'Central Asia'
 'Central Europe' 'Central Europe, Eastern Europe, and Central Asia'
 'Central Latin America' 'Central Sub-Saharan Africa' 'Chad' 'Chile'
 'China' 'Colombia' 'Comoros' 'Congo' 'Costa Rica' "Cote d'Ivoire"
 'Croatia' 'Cuba' 'Cyprus' 'Czech Republic' 'Democratic Republic of Congo'
 'Denmark' 'Djibouti' 'Dominica' 'Dominican Republic' 'East Asia'
 'Eastern Europe' 'Eastern Sub-Saharan Africa' 'Ecuador' 'Egypt'
 'El Salvador' 'England' 'Equatorial Guinea' 'Eritrea' 'Estonia'
 'Ethiopia' 'Fiji' 'Finland' 'France' 'Gabon' 'Gambia' 'Georgia' 'Germany'
 'Ghana' 'Greece' 'Greenland' 'Grenada' 'Guam' 'Guatemala' 'Guinea'
 'Guinea-Bissau' 'Guyana' 'Haiti' 'High SDI' 'High-income'
 'High-income Asia Pacific' 'High-middle SDI' 'Honduras' 'Hungary'
 'Iceland' 'India' 'Indonesia' 'Iran' 'Iraq' 'Ireland' 'Israel' 'Italy'
 'Jamaica' 'Japan' 'Jordan' 'Kazakhstan' 'Kenya' 'Kiribati' 'Kuwait'
 'Kyrgyzstan' 'Laos' 'Latin America and Caribbean' 'Latvia' 'Lebanon'
 'Lesotho' 'Liberia' 'Libya' 'Lithuania' 'Low SDI' 'Low-middle SDI'
 'Luxembourg' 'Macedonia' 'Madagascar' 'Malawi' 'Malaysia' 'Maldives'
 'Mali' 'Malta' 'Marshall Islands' 'Mauritania' 'Mauritius' 'Mexico'
 'Micronesia (country)' 'Middle SDI' 'Moldova' 'Mongolia' 'Montenegro'
 'Morocco' 'Mozambique' 'Myanmar' 'Namibia' 'Nepal' 'Netherlands'
 'New Zealand' 'Nicaragua' 'Niger' 'Nigeria'
 'North Africa and Middle East' 'North America' 'North Korea'
 'Northern Ireland' 'Northern Mariana Islands' 'Norway' 'Oceania' 'Oman'
 'Pakistan' 'Palestine' 'Panama' 'Papua New Guinea' 'Paraguay' 'Peru'
 'Philippines' 'Poland' 'Portugal' 'Puerto Rico' 'Qatar' 'Romania'
 'Russia' 'Rwanda' 'Saint Lucia' 'Saint Vincent and the Grenadines'
 'Samoa' 'Sao Tome and Principe' 'Saudi Arabia' 'Scotland' 'Senegal'
 'Serbia' 'Seychelles' 'Sierra Leone' 'Singapore' 'Slovakia' 'Slovenia'
 'Solomon Islands' 'Somalia' 'South Africa' 'South Asia' 'South Korea'
 'South Sudan' 'Southeast Asia' 'Southeast Asia, East Asia, and Oceania'
 'Southern Latin America' 'Southern Sub-Saharan Africa' 'Spain'
 'Sri Lanka' 'Sub-Saharan Africa' 'Sudan' 'Suriname' 'Swaziland' 'Sweden'
 'Switzerland' 'Syria' 'Taiwan' 'Tajikistan' 'Tanzania' 'Thailand' 'Timor'
 'Togo' 'Tonga' 'Trinidad and Tobago' 'Tropical Latin America' 'Tunisia'
 'Turkey' 'Turkmenistan' 'Uganda' 'Ukraine' 'United Arab Emirates'
 'United Kingdom' 'United States' 'United States Virgin Islands' 'Uruguay'
 'Uzbekistan' 'Vanuatu' 'Venezuela' 'Vietnam' 'Wales' 'Western Europe'
 'Western Sub-Saharan Africa' 'World' 'Yemen' 'Zambia' 'Zimbabwe' 'Entity'
 'Africa' 'Anguilla' 'Aruba' 'Asia' 'Bonaire Sint Eustatius and Saba'
 'British Virgin Islands' 'Cayman Islands' 'Channel Islands'
 'Cook Islands' 'Curacao' 'Europe' 'Faeroe Islands' 'Falkland Islands'
 'French Guiana' 'French Polynesia' 'Gibraltar' 'Guadeloupe' 'Hong Kong'
 'Isle of Man' 'Latin America' 'Liechtenstein' 'Macao' 'Martinique'
 'Mayotte' 'Monaco' 'Montserrat' 'Nauru' 'New Caledonia' 'Niue' 'Palau'
 'Reunion' 'Saint Barthlemy' 'Saint Helena' 'Saint Kitts and Nevis'
 'Saint Martin (French part)' 'Saint Pierre and Miquelon' 'San Marino'
 'Sint Maarten (Dutch part)' 'Tokelau' 'Turks and Caicos Islands' 'Tuvalu'
 'Vatican' 'Wallis and Futuna' 'Western Sahara']

In [18]:
# builting the dataframe
    # create new df with countries we're interested in studying
    # fix the index 
    # added variable for whether it has universal healthcare or not
    
developed = health.loc[health['Entity'].isin(['United States','Japan','Argentina','Australia','United Kingdom', 'South Korea','Denmark','Canada','France','Taiwan','Uruguay','Germany'])]

developed = developed.reset_index(drop=True)

developed = developed.drop('index', axis=1)

developed.head()

# have universal care or practically universal care (for example may be small co-pays)
developed["Universal Care"] = np.nan

#if [developed['Entity'] == 'United Staes']:
#    developed["Universal Care"] = 0
#else: 
#    developed["Universal Care"] = 1
             
#developed.loc[developed['Entity'] == 'United Staes']          

#developed['Entity'].unique()


#developed["Universal Care"] = np.where(developed['Entity'] == 'United Staes', 0,1) 


#developed.loc[developed['Entity'] == 'United Staes']

developed.head()

,Entity,Code,Year,Schizophrenia (%),Bipolar disorder (%),Eating disorders (%),Anxiety disorders (%),Drug use disorders (%),Depression (%),Alcohol use disorders (%),Universal Care
0,Argentina,ARG,1990,0.194422,0.755674,0.323686,6.165921,0.919424,3.569180,1.918939,NaN
1,Argentina,ARG,1991,0.194184,0.756386,0.326904,6.174471,0.920323,3.579068,2.022040,NaN
2,Argentina,ARG,1992,0.194034,0.757139,0.330504,6.182707,0.921296,3.588855,2.116047,NaN
3,Argentina,ARG,1993,0.193973,0.757909,0.334286,6.190356,0.921620,3.597366,2.193307,NaN
4,Argentina,ARG,1994,0.194004,0.758686,0.338418,6.197271,0.921581,3.606913,2.246206,NaN